# Automatically generated by create_hash_dict "--output" "tools/bazel_hash_dict.bzl"

BAZEL_HASH_DICT = {
    "0.6.0": {
        "darwin-x86_64": "932b52ff9ec5b753e57643dce8689622d3a0d6ec34a288fb57cf776b50674226",
        "linux-x86_64": "6e30f1aa3dcbb9c022251e60ac445244f66535ea627afd1780eafe2de19dab8f",
    },
    "0.6.1": {
        "darwin-x86_64": "f404b0eb51ed457d932457e13da1ef79de040ebf52b2eacdaff3b57bb023b501",
        "linux-x86_64": "b2a8dd2ca12e968300c60489444453a24b19c388a1a71f560ae84aa1d18575bb",
    },
    "0.7.0": {
        "darwin-x86_64": "ea9a568c5357d3f6911701f4e3814c9800e5edfc618cf403602ed5bd8ad96f96",
        "linux-x86_64": "e72baaef66b09e5f765c0c7d3c216cda0c8c48368524605705cfe14a584e9942",
    },
    "0.8.0": {
        "darwin-x86_64": "6aa70de116ad8e7c3f65541dee5126fb7afabb45092f2c3213b9fca892ec3427",
        "linux-x86_64": "ea7c86a32c2f5e5c82d81c637165113d0049d1eada9faf4b7023940c76671d50",
    },
    "0.8.1": {
        "darwin-x86_64": "647a7071a7066c2ebe4872983f4857aa8686245f06b16a53e980a7bfa59f366e",
        "linux-x86_64": "297ca06975bf47a5c9ffb7cb3482fa000486f50a4e8074e51ab634887d807b78",
    },
    "0.9.0": {
        "darwin-x86_64": "95c6dbe99dbc8f0c722d4fcbf8541e26892d50e3208b935c9722abcac2447f87",
        "linux-x86_64": "dbe4f90e0340c4c415519152fbc30d1201c882877fccd515ee255e3a107a2cfb",
    },
    "0.10.0": {
        "darwin-x86_64": "636d1ce68616a903928798908c16fb68ebb85eb28d2f18fb215f4d09f3bb05ca",
        "linux-x86_64": "ffff2632e32d5009fd48b7f51971a66012eefa2004c6448c13dc3976ad1db6b0",
    },
    "0.10.1": {
        "darwin-x86_64": "bb53083306490a6fd1a30bc208e34d11e1e1684f7ab2fb319c9a8751c443d625",
        "linux-x86_64": "1e3ff1cdff1527ebf9c53b0c5f474e15847fdb77065e972a56c0fd863ee3f621",
    },
    "0.11.0": {
        "darwin-x86_64": "8d60c3944ccd220f71bcbf034e416f0000f196cecae2dfd3661a181e22565b65",
        "linux-x86_64": "687305c38a7786f3f4d74e13f31a05ae2a5ef50ef1736f85b749ec047a97e73b",
    },
    "0.12.0": {
        "darwin-x86_64": "a1e0e08959880de3c360006718332b6426afa40a09b4353aae552e40f411d0ee",
        "linux-x86_64": "1af7a70cc2c5180765ed2f0da366c625fac89e6656dedc008320d46eb1f75e20",
    },
    "0.13.0": {
        "darwin-x86_64": "f7ad77c509eda9bc6cd3c98945858e278265a9551a1d7b31f38558a296b71027",
        "linux-x86_64": "c90ed6d8478fd543d936702d2eb3ed034f46b2223fac790598db70c161552418",
    },
    "0.13.1": {
        "darwin-x86_64": "7eca890f253d64a334108db7017214693a87d4af1cd7c6239b1b89fa4a9dd802",
        "linux-x86_64": "a2f2ef984193119663afeb4b8cecf2847bfec578d2f1f9256c403589cc52465d",
    },
    "0.14.0": {
        "darwin-x86_64": "86126884108628259454961137d3aee6aa62b2348ee8deb53e139447b1c4efb2",
        "linux-x86_64": "34488cd55f95668cfad45874d9d58a220ea8233beede60ade1b036ebc661c1d0",
    },
    "0.14.1": {
        "darwin-x86_64": "0bdf63909ef9ba446a2d7cd077edb3aaf4d63b725e82e7cdcb69df482df61a3c",
        "linux-x86_64": "7b14e4fc76bf85c4abf805833e99f560f124a3b96d56e0712c693e94e19d1376",
    },
}
